# Change these first
owner: corptek # Your GitHub organization or username, where this repository lives
repo: uptime-final # The name of this repository

sites:
  - name: Ecango Website
    url: https://www.ecango.com
  - name: Ecango BE
    url: https://app.ecango.com/do/ping/
  - name: Ecango AI
    url: https://transcriber.ecango.com/ping/
  - name: downtest
    url: https://somecrazydomain.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: uptime.ecango.com
  baseUrl: /uptime-final
  favicon: https://app.ecango.com/favicon.ico
  logoUrl: https://app.ecango.com/favicon.ico
  name: Ecango System Status
  introTitle: "**Ecango Status**"
  introMessage: 
  navbar:
    - title: Status
      href: /
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
